on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: '12'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build Release with Gradle
        run: |
          ./gradlew :app:assembleRelease --daemon --parallel
          
      - name: Sign Apk
        run: |
          PASSWD=$(echo $RANDOM | md5sum | head -c 15)
          ALIAS="random"
          keytool -genkey -noprompt -v -keystore android.keystore -alias ${ALIAS} -keyalg RSA -keysize 2048 -validity 10000 -keypass ${PASSWD} -storepass ${PASSWD} -dname "CN=xx, OU=xx, O=xx, L=xx, S=xx, C=xx"
          apksigner=${ANDROID_SDK_ROOT}/build-tools/30.0.3/apksigner
          apksigner sign --ks ./android.keystore \
          --ks-pass pass:${PASSWD} \
          --ks-key-alias ${ALIAS} \
          --key-pass pass:${PASSWD} \
          --in "./app/build/outputs/apk/release/app-release-unsigned.apk" \
          --out "./app/build/outputs/apk/release/app-release-signed.apk"

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: SNAPSHOT
          path: ./app/build/
          
      - name: Upload Apks
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: Apks
          path: ./app/build/outputs/apk/release/
