on: [push, pull_request]

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - name: Check out
        uses: actions/checkout@v2

      - name: Gradle wrapper validation
        uses: gradle/wrapper-validation-action@v1

      - name: Set up JDK 12
        uses: actions/setup-java@v1
        with:
          java-version: '12'

      - name: Cache Gradle
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle-
          
      - name: Make gradlew executable
        run: chmod +x ./gradlew
        
      - name: Build Release with Gradle
        run: |
          ./gradlew :app:assembleRelease --daemon --parallel

      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        if: runner.os == 'Linux'
        with:
          name: SNAPSHOT
          path: ./app/